name: Enforce PR Template

on:
  pull_request:
    branches:
      - main
      - develop
      - release_*
    types: [opened, edited]

jobs:
  validate-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR description
        env:
          PR_BODY: ${{ github.event.pull_request.body }}
        run: |
          set -x
          REQUIRED_SECTIONS=("Summary" "Changes" "Issue Link")
          MISSING_SECTIONS=()
          for SECTION in "${REQUIRED_SECTIONS[@]}"; do
            if [[ ! "$PR_BODY" =~ $SECTION ]]; then
              MISSING_SECTIONS+=("$SECTION")
            fi
          done
          MISSING_SECTIONS_ARR_LENGTH=0

          for _ in "${MISSING_SECTIONS[@]}"; do
            ((MISSING_SECTIONS_ARR_LENGTH++))
          done

          if [ ${MISSING_SECTIONS_ARR_LENGTH} -ne 0 ]; then
            echo "❌ ERROR: PR must include the required sections: ${MISSING_SECTIONS[*]}"
            exit 1
          fi
          
      - name: Check JIRA Ticket
        env:
          PR_BODY: ${{ github.event.pull_request.body }}
        run: |
          if [[ ! "$PR_BODY" =~ [A-Z]+-[0-9]+ ]]; then
            echo "❌ ERROR: PR description must include a JIRA Ticket (e.g., ABC-1234) in the 'Issue Link' section."
            exit 1
          fi